builds:
  - env:
      - GODEBUG=cgocheck=0
    main: ./plugin
    binary: libdocker.so
    goos:
      - linux
    goarch:
      - amd64
    flags: -buildmode=c-shared
checksum:
  name_template: "checksums.txt"